version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
